version: '3.6'
services:
  web:
    build: .
    environment:
      MIX_ENV: dev
      ERL_MAX_PORTS: 1024
    env_file:
      - .env
    ports:
      - '4000:4000'
    hostname: 'amboseli'
    restart: unless-stopped
    volumes:
      - .:/app
